name: SQLFluff lint dbt models

on:
  pull_request:

jobs:
  sqlfluff-lint-models:
    name: Lint dbt models using SQLFluff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install Python packages
        run: python -m pip install pip==21.2.3 dbt-snowflake~=1.6.0 sqlfluff-templater-dbt